import { PrismaClient } from '@prisma/client';

type SeedOpt = { category: string; code: string; label: string; sortOrder: number };

const SEED: SeedOpt[] = [
  // Organization
  { category: 'ORGANIZATION', code: 'GANDHINAGAR_UNIVERSITY', label: 'Gandhinagar University', sortOrder: 1 },
  { category: 'ORGANIZATION', code: 'PLATINUM_FOUNDATION', label: 'Platinum Foundation', sortOrder: 2 },

  // Blood group
  { category: 'BLOOD_GROUP', code: 'A_POS', label: 'A+', sortOrder: 1 },
  { category: 'BLOOD_GROUP', code: 'A_NEG', label: 'A−', sortOrder: 2 },
  { category: 'BLOOD_GROUP', code: 'B_POS', label: 'B+', sortOrder: 3 },
  { category: 'BLOOD_GROUP', code: 'B_NEG', label: 'B−', sortOrder: 4 },
  { category: 'BLOOD_GROUP', code: 'O_POS', label: 'O+', sortOrder: 5 },
  { category: 'BLOOD_GROUP', code: 'O_NEG', label: 'O−', sortOrder: 6 },
  { category: 'BLOOD_GROUP', code: 'AB_POS', label: 'AB+', sortOrder: 7 },
  { category: 'BLOOD_GROUP', code: 'AB_NEG', label: 'AB−', sortOrder: 8 },

  // Gender
  { category: 'GENDER', code: 'MALE', label: 'Male', sortOrder: 1 },
  { category: 'GENDER', code: 'FEMALE', label: 'Female', sortOrder: 2 },
  { category: 'GENDER', code: 'OTHER', label: 'Other', sortOrder: 3 },

  // Marital
  { category: 'MARITAL_STATUS', code: 'SINGLE', label: 'Single', sortOrder: 1 },
  { category: 'MARITAL_STATUS', code: 'MARRIED', label: 'Married', sortOrder: 2 },
  { category: 'MARITAL_STATUS', code: 'DIVORCED', label: 'Divorced', sortOrder: 3 },
  { category: 'MARITAL_STATUS', code: 'WIDOWED', label: 'Widowed', sortOrder: 4 },

  // Nationality / tongue / caste / religion
  { category: 'NATIONALITY', code: 'INDIAN', label: 'Indian', sortOrder: 1 },
  { category: 'MOTHER_TONGUE', code: 'GUJARATI', label: 'Gujarati', sortOrder: 1 },
  { category: 'MOTHER_TONGUE', code: 'HINDI', label: 'Hindi', sortOrder: 2 },
  { category: 'MOTHER_TONGUE', code: 'ENGLISH', label: 'English', sortOrder: 3 },
  { category: 'CASTE_CATEGORY', code: 'OPEN', label: 'Open / General', sortOrder: 1 },
  { category: 'CASTE_CATEGORY', code: 'OBC', label: 'OBC', sortOrder: 2 },
  { category: 'CASTE_CATEGORY', code: 'SC', label: 'SC', sortOrder: 3 },
  { category: 'CASTE_CATEGORY', code: 'ST', label: 'ST', sortOrder: 4 },
  { category: 'CASTE_CATEGORY', code: 'EWS', label: 'EWS', sortOrder: 5 },
  { category: 'RELIGION', code: 'HINDU', label: 'Hindu', sortOrder: 1 },
  { category: 'RELIGION', code: 'MUSLIM', label: 'Muslim', sortOrder: 2 },
  { category: 'RELIGION', code: 'CHRISTIAN', label: 'Christian', sortOrder: 3 },
  { category: 'RELIGION', code: 'SIKH', label: 'Sikh', sortOrder: 4 },
  { category: 'RELIGION', code: 'JAIN', label: 'Jain', sortOrder: 5 },
  { category: 'RELIGION', code: 'OTHER', label: 'Other', sortOrder: 6 },

  // Employment
  { category: 'EMPLOYEE_CATEGORY', code: 'TEACHING', label: 'Teaching', sortOrder: 1 },
  { category: 'EMPLOYEE_CATEGORY', code: 'NON_TEACHING', label: 'Non Teaching', sortOrder: 2 },
  { category: 'EMPLOYEE_CATEGORY', code: 'CONTRACT', label: 'Contract', sortOrder: 3 },
  { category: 'EMPLOYEE_CATEGORY', code: 'VISITING', label: 'Visiting', sortOrder: 4 },
  { category: 'APPOINTMENT_TYPE', code: 'FULL_TIME_REGULAR', label: 'Full Time Regular', sortOrder: 1 },
  { category: 'APPOINTMENT_TYPE', code: 'FULL_TIME_CONTRACT', label: 'Full Time Contract', sortOrder: 2 },
  { category: 'APPOINTMENT_TYPE', code: 'PART_TIME', label: 'Part Time', sortOrder: 3 },
  { category: 'APPOINTMENT_TYPE', code: 'VISITING', label: 'Visiting', sortOrder: 4 },
  { category: 'APPOINTMENT_TYPE', code: 'DEPUTATION', label: 'Deputation', sortOrder: 5 },
  { category: 'SHIFT', code: 'GENERAL', label: 'General', sortOrder: 1 },
  { category: 'SHIFT', code: 'MORNING', label: 'Morning', sortOrder: 2 },
  { category: 'SHIFT', code: 'EVENING', label: 'Evening', sortOrder: 3 },

  // Family
  { category: 'FAMILY_RELATION', code: 'FATHER', label: 'Father', sortOrder: 1 },
  { category: 'FAMILY_RELATION', code: 'MOTHER', label: 'Mother', sortOrder: 2 },
  { category: 'FAMILY_RELATION', code: 'SPOUSE', label: 'Spouse', sortOrder: 3 },
  { category: 'FAMILY_RELATION', code: 'SON', label: 'Son', sortOrder: 4 },
  { category: 'FAMILY_RELATION', code: 'DAUGHTER', label: 'Daughter', sortOrder: 5 },
  { category: 'FAMILY_RELATION', code: 'BROTHER', label: 'Brother', sortOrder: 6 },
  { category: 'FAMILY_RELATION', code: 'SISTER', label: 'Sister', sortOrder: 7 },
  { category: 'FAMILY_RELATION', code: 'OTHER', label: 'Other', sortOrder: 8 },

  // Academic
  { category: 'DEGREE_TYPE', code: 'SSC', label: 'SSC', sortOrder: 1 },
  { category: 'DEGREE_TYPE', code: 'HSC', label: 'HSC', sortOrder: 2 },
  { category: 'DEGREE_TYPE', code: 'DIPLOMA', label: 'Diploma', sortOrder: 3 },
  { category: 'DEGREE_TYPE', code: 'BACHELOR', label: 'Bachelor', sortOrder: 4 },
  { category: 'DEGREE_TYPE', code: 'MASTER', label: 'Master', sortOrder: 5 },
  { category: 'DEGREE_TYPE', code: 'PHD', label: 'PhD', sortOrder: 6 },
  { category: 'DEGREE_TYPE', code: 'OTHER', label: 'Other', sortOrder: 7 },
  { category: 'ACADEMIC_MEDIUM', code: 'GUJARATI', label: 'Gujarati', sortOrder: 1 },
  { category: 'ACADEMIC_MEDIUM', code: 'HINDI', label: 'Hindi', sortOrder: 2 },
  { category: 'ACADEMIC_MEDIUM', code: 'ENGLISH', label: 'English', sortOrder: 3 },
  { category: 'ACADEMIC_MEDIUM', code: 'MARATHI', label: 'Marathi', sortOrder: 4 },
  { category: 'ACADEMIC_MEDIUM', code: 'OTHER', label: 'Other', sortOrder: 5 },
  { category: 'HSC_STREAM', code: 'SCIENCE', label: 'Science', sortOrder: 1 },
  { category: 'HSC_STREAM', code: 'COMMERCE', label: 'Commerce', sortOrder: 2 },
  { category: 'HSC_STREAM', code: 'ARTS_HUMANITIES', label: 'Arts / Humanities', sortOrder: 3 },

  // Experience
  { category: 'EXPERIENCE_TYPE', code: 'TEACHING', label: 'Teaching', sortOrder: 1 },
  { category: 'EXPERIENCE_TYPE', code: 'INDUSTRY', label: 'Industry', sortOrder: 2 },
  { category: 'EXPERIENCE_TYPE', code: 'RESEARCH', label: 'Research', sortOrder: 3 },
  { category: 'EXPERIENCE_TYPE', code: 'ADMINISTRATIVE', label: 'Administrative', sortOrder: 4 },
  { category: 'EXPERIENCE_TYPE', code: 'CONSULTANCY', label: 'Consultancy', sortOrder: 5 },
  { category: 'EXPERIENCE_TYPE', code: 'OTHER', label: 'Other', sortOrder: 6 },

  // Banks (starter set)
  { category: 'BANK_NAME', code: 'SBI', label: 'State Bank of India', sortOrder: 1 },
  { category: 'BANK_NAME', code: 'HDFC', label: 'HDFC Bank', sortOrder: 2 },
  { category: 'BANK_NAME', code: 'ICICI', label: 'ICICI Bank', sortOrder: 3 },
  { category: 'BANK_NAME', code: 'AXIS', label: 'Axis Bank', sortOrder: 4 },
  { category: 'BANK_NAME', code: 'BOB', label: 'Bank of Baroda', sortOrder: 5 },

  // Recruitment
  { category: 'INTERVIEW_TYPE', code: 'HR_SCREEN', label: 'HR Screen', sortOrder: 1 },
  { category: 'INTERVIEW_TYPE', code: 'TECHNICAL', label: 'Technical', sortOrder: 2 },
  { category: 'INTERVIEW_TYPE', code: 'DIRECTOR', label: 'Director', sortOrder: 3 },
  { category: 'INTERVIEW_TYPE', code: 'FINAL', label: 'Final Round', sortOrder: 4 },

  { category: 'INTERVIEW_STATUS', code: 'INTERVIEW_SCHEDULED', label: 'Interview Scheduled', sortOrder: 1 },
  { category: 'INTERVIEW_STATUS', code: 'INTERVIEW_ATTENDED', label: 'Interview Attended', sortOrder: 2 },
  { category: 'INTERVIEW_STATUS', code: 'NOT_CAME', label: 'Not came for Interview', sortOrder: 3 },
  { category: 'INTERVIEW_STATUS', code: 'RESCHEDULED', label: 'Rescheduled', sortOrder: 4 },
  { category: 'INTERVIEW_STATUS', code: 'SELECTED_FOR_NEXT_ROUND', label: 'Selected for Next Round', sortOrder: 5 },
  { category: 'INTERVIEW_STATUS', code: 'FINAL_ROUND', label: 'Final Round', sortOrder: 6 },
  { category: 'INTERVIEW_STATUS', code: 'SELECTED', label: 'Selected', sortOrder: 7 },
  { category: 'INTERVIEW_STATUS', code: 'ON_HOLD', label: 'On Hold', sortOrder: 8 },
  { category: 'INTERVIEW_STATUS', code: 'REJECTED', label: 'Rejected', sortOrder: 9 },
  { category: 'INTERVIEW_STATUS', code: 'DROPOUT', label: 'Dropout / Backout', sortOrder: 10 },

  { category: 'CANDIDATE_SOURCE', code: 'REFERRAL', label: 'Referral', sortOrder: 1 },
  { category: 'CANDIDATE_SOURCE', code: 'NAUKRI', label: 'Naukri', sortOrder: 2 },
  { category: 'CANDIDATE_SOURCE', code: 'WALK_IN', label: 'Walk-in', sortOrder: 3 },
  { category: 'CANDIDATE_SOURCE', code: 'LINKEDIN', label: 'LinkedIn', sortOrder: 4 },
  { category: 'CANDIDATE_SOURCE', code: 'WEBSITE', label: 'Website', sortOrder: 5 },
  { category: 'CANDIDATE_SOURCE', code: 'OTHER', label: 'Other', sortOrder: 6 },

  // ERP Projects
  { category: 'PROJECT_CATEGORY', code: 'RESIDENTIAL', label: 'Residential', sortOrder: 1 },
  { category: 'PROJECT_CATEGORY', code: 'COMMERCIAL', label: 'Commercial', sortOrder: 2 },
  { category: 'PROJECT_CATEGORY', code: 'MIXED_USE', label: 'Mixed Use', sortOrder: 3 },
  { category: 'PROJECT_SUB_CATEGORY', code: 'APARTMENT', label: 'Apartment', sortOrder: 1 },
  { category: 'PROJECT_SUB_CATEGORY', code: 'VILLA', label: 'Villa', sortOrder: 2 },
  { category: 'PROJECT_SUB_CATEGORY', code: 'PLOT', label: 'Plot', sortOrder: 3 },
  { category: 'PROJECT_SUB_CATEGORY', code: 'OFFICE', label: 'Office', sortOrder: 4 },
  { category: 'PROJECT_STRUCTURE', code: 'HIGH_RISE', label: 'High Rise', sortOrder: 1 },
  { category: 'PROJECT_STRUCTURE', code: 'LOW_RISE', label: 'Low Rise', sortOrder: 2 },
  { category: 'PROJECT_STRUCTURE', code: 'ROW_HOUSE', label: 'Row House', sortOrder: 3 },
  { category: 'PROJECT_SEGMENT', code: 'AFFORDABLE', label: 'Affordable', sortOrder: 1 },
  { category: 'PROJECT_SEGMENT', code: 'MID', label: 'Mid', sortOrder: 2 },
  { category: 'PROJECT_SEGMENT', code: 'PREMIUM', label: 'Premium', sortOrder: 3 },
  { category: 'PROJECT_STATUS', code: 'ACTIVE', label: 'Active', sortOrder: 1 },
  { category: 'PROJECT_STATUS', code: 'ON_HOLD', label: 'On Hold', sortOrder: 2 },
  { category: 'PROJECT_STATUS', code: 'COMPLETED', label: 'Completed', sortOrder: 3 },
  { category: 'PROJECT_STATUS', code: 'INACTIVE', label: 'Inactive', sortOrder: 4 },
  { category: 'PROJECT_AREA_UNIT', code: 'SQ_FT', label: 'Sq Ft', sortOrder: 1 },
  { category: 'PROJECT_AREA_UNIT', code: 'SQ_M', label: 'Sq M', sortOrder: 2 },
  { category: 'PROJECT_AREA_UNIT', code: 'SQ_YD', label: 'Sq Yd', sortOrder: 3 },
  { category: 'PROJECT_AREA_UNIT', code: 'ACRE', label: 'Acre', sortOrder: 4 },
  { category: 'PROJECT_COUNTRY', code: 'INDIA', label: 'India', sortOrder: 1 },
  { category: 'PROJECT_STATE', code: 'GUJARAT', label: 'Gujarat', sortOrder: 1 },
  { category: 'PROJECT_CITY', code: 'AHMEDABAD', label: 'Ahmedabad', sortOrder: 1 },
  { category: 'PROJECT_CITY', code: 'GANDHINAGAR', label: 'Gandhinagar', sortOrder: 2 },
  { category: 'PROJECT_LOCATION_AREA', code: 'SG_HIGHWAY', label: 'S.G. Highway', sortOrder: 1 },
  { category: 'PROJECT_LOCATION_AREA', code: 'BODELI', label: 'Bopal', sortOrder: 2 },
  { category: 'PROJECT_AMENITY', code: 'CLUBHOUSE', label: 'Clubhouse', sortOrder: 1 },
  { category: 'PROJECT_AMENITY', code: 'SWIMMING_POOL', label: 'Swimming Pool', sortOrder: 2 },
  { category: 'PROJECT_AMENITY', code: 'GYM', label: 'Gym', sortOrder: 3 },
  { category: 'PROJECT_LIVABILITY', code: 'EXCELLENT', label: 'Excellent', sortOrder: 1 },
  { category: 'PROJECT_LIVABILITY', code: 'GOOD', label: 'Good', sortOrder: 2 },
  { category: 'PROJECT_LIVABILITY', code: 'AVERAGE', label: 'Average', sortOrder: 3 },
  { category: 'PROJECT_BANK_TIE_UP', code: 'SBI', label: 'State Bank of India', sortOrder: 1 },
  { category: 'PROJECT_BANK_TIE_UP', code: 'HDFC', label: 'HDFC Bank', sortOrder: 2 },
  { category: 'PROJECT_BANK_TIE_UP', code: 'ICICI', label: 'ICICI Bank', sortOrder: 3 },
  { category: 'PROJECT_DEV_AUTHORITY', code: 'AUDA', label: 'AUDA', sortOrder: 1 },
  { category: 'PROJECT_DEV_AUTHORITY', code: 'AMC', label: 'AMC', sortOrder: 2 },
  { category: 'PROJECT_DEV_AUTHORITY', code: 'GMC', label: 'GMC', sortOrder: 3 },
  { category: 'PROJECT_ELEC_PROVIDER', code: 'UGVCL', label: 'UGVCL', sortOrder: 1 },
  { category: 'PROJECT_ELEC_PROVIDER', code: 'TORRENT', label: 'Torrent Power', sortOrder: 2 },
  { category: 'PROJECT_DOCUMENT_TYPE', code: 'BROCHURE', label: 'Brochure', sortOrder: 1 },
  { category: 'PROJECT_DOCUMENT_TYPE', code: 'LAYOUT', label: 'Layout', sortOrder: 2 },
  { category: 'PROJECT_DOCUMENT_TYPE', code: 'APPROVAL', label: 'Approval', sortOrder: 3 },
  { category: 'PROJECT_DOCUMENT_TYPE', code: 'OTHER', label: 'Other', sortOrder: 4 },
  { category: 'PROJECT_TOWER_STATUS', code: 'ACTIVE', label: 'Active', sortOrder: 1 },
  { category: 'PROJECT_TOWER_STATUS', code: 'ON_HOLD', label: 'On Hold', sortOrder: 2 },
  { category: 'PROJECT_TOWER_STATUS', code: 'COMPLETED', label: 'Completed', sortOrder: 3 },
  { category: 'PROJECT_UNIT_TYPE', code: 'STUDIO', label: 'Studio', sortOrder: 1 },
  { category: 'PROJECT_UNIT_TYPE', code: '1BHK', label: '1 BHK', sortOrder: 2 },
  { category: 'PROJECT_UNIT_TYPE', code: '2BHK', label: '2 BHK', sortOrder: 3 },
  { category: 'PROJECT_UNIT_TYPE', code: '3BHK', label: '3 BHK', sortOrder: 4 },
  { category: 'PROJECT_UNIT_TYPE', code: '4BHK', label: '4 BHK', sortOrder: 5 },
  { category: 'PROJECT_UNIT_TYPE', code: 'PENTHOUSE', label: 'Penthouse', sortOrder: 6 },
  { category: 'PROJECT_UNIT_TYPE', code: 'SHOP', label: 'Shop', sortOrder: 7 },
  { category: 'PROJECT_UNIT_TYPE', code: 'OFFICE', label: 'Office', sortOrder: 8 },
  { category: 'PROJECT_UNIT_STATUS', code: 'AVAILABLE', label: 'Available', sortOrder: 1 },
  { category: 'PROJECT_UNIT_STATUS', code: 'HOLD', label: 'On Hold', sortOrder: 2 },
  { category: 'PROJECT_UNIT_STATUS', code: 'BOOKED', label: 'Booked', sortOrder: 3 },
  { category: 'PROJECT_UNIT_STATUS', code: 'SOLD', label: 'Sold', sortOrder: 4 },
  { category: 'PROJECT_UNIT_STATUS', code: 'BLOCKED', label: 'Blocked', sortOrder: 5 },
  { category: 'PROJECT_UNIT_FACING', code: 'NORTH', label: 'North', sortOrder: 1 },
  { category: 'PROJECT_UNIT_FACING', code: 'SOUTH', label: 'South', sortOrder: 2 },
  { category: 'PROJECT_UNIT_FACING', code: 'EAST', label: 'East', sortOrder: 3 },
  { category: 'PROJECT_UNIT_FACING', code: 'WEST', label: 'West', sortOrder: 4 },
  { category: 'PROJECT_UNIT_FACING', code: 'NORTH_EAST', label: 'North East', sortOrder: 5 },
  { category: 'PROJECT_UNIT_FACING', code: 'NORTH_WEST', label: 'North West', sortOrder: 6 },
  { category: 'PROJECT_UNIT_FACING', code: 'SOUTH_EAST', label: 'South East', sortOrder: 7 },
  { category: 'PROJECT_UNIT_FACING', code: 'SOUTH_WEST', label: 'South West', sortOrder: 8 },
  { category: 'PROJECT_UNIT_CATEGORY', code: 'STANDARD', label: 'Standard', sortOrder: 1 },
  { category: 'PROJECT_UNIT_CATEGORY', code: 'CORNER', label: 'Corner', sortOrder: 2 },
  { category: 'PROJECT_UNIT_CATEGORY', code: 'PREMIUM', label: 'Premium', sortOrder: 3 },

  // Work Orders
  { category: 'WO_MEASUREMENT_UNIT', code: 'PCS', label: 'PCS', sortOrder: 1 },
  { category: 'WO_MEASUREMENT_UNIT', code: 'SQ_FT', label: 'Sq Ft', sortOrder: 2 },
  { category: 'WO_MEASUREMENT_UNIT', code: 'SQ_M', label: 'Sq M', sortOrder: 3 },
  { category: 'WO_MEASUREMENT_UNIT', code: 'RMT', label: 'Rmt', sortOrder: 4 },
  { category: 'WO_MEASUREMENT_UNIT', code: 'KG', label: 'Kg', sortOrder: 5 },
  { category: 'WO_MEASUREMENT_UNIT', code: 'LTR', label: 'Ltr', sortOrder: 6 },
  { category: 'WO_CATEGORY', code: 'CIVIL', label: 'Civil', sortOrder: 1 },
  { category: 'WO_CATEGORY', code: 'ELECTRICAL', label: 'Electrical', sortOrder: 2 },
  { category: 'WO_CATEGORY', code: 'PLUMBING', label: 'Plumbing', sortOrder: 3 },
  { category: 'WO_CATEGORY', code: 'FINISHING', label: 'Finishing', sortOrder: 4 },

  // Contractors
  { category: 'CONTRACTOR_TDS', code: 'TDS_1', label: 'TDS 1%', sortOrder: 1 },
  { category: 'CONTRACTOR_TDS', code: 'TDS_2', label: 'TDS 2%', sortOrder: 2 },
  { category: 'CONTRACTOR_TDS', code: 'TCS_1', label: 'TCS 1%', sortOrder: 3 },
  { category: 'CONTRACTOR_TDS', code: 'TCS_2', label: 'TCS 2%', sortOrder: 4 },
  { category: 'CONTRACTOR_TDS', code: 'NIL', label: 'Nil', sortOrder: 5 },
  { category: 'CONTRACTOR_TYPE', code: 'CIVIL', label: 'Civil', sortOrder: 1 },
  { category: 'CONTRACTOR_TYPE', code: 'ELECTRICAL', label: 'Electrical', sortOrder: 2 },
  { category: 'CONTRACTOR_TYPE', code: 'PLUMBING', label: 'Plumbing', sortOrder: 3 },
  { category: 'CONTRACTOR_TYPE', code: 'FINISHING', label: 'Finishing', sortOrder: 4 },
  { category: 'CONTRACTOR_TYPE', code: 'GENERAL', label: 'General', sortOrder: 5 },
  { category: 'CONTRACTOR_ADDRESS_TYPE', code: 'BILLING', label: 'Billing Address', sortOrder: 1 },
  { category: 'CONTRACTOR_ADDRESS_TYPE', code: 'OFFICE', label: 'Office Address', sortOrder: 2 },
  { category: 'CONTRACTOR_ADDRESS_TYPE', code: 'SITE', label: 'Site Address', sortOrder: 3 },
  { category: 'CONTRACTOR_ADDRESS_TYPE', code: 'REGISTERED', label: 'Registered Address', sortOrder: 4 },
  { category: 'CONTRACTOR_COUNTRY', code: 'INDIA', label: 'India', sortOrder: 1 },
  { category: 'CONTRACTOR_STATE', code: 'GUJARAT', label: 'Gujarat', sortOrder: 1 },
  { category: 'CONTRACTOR_STATE', code: 'MAHARASHTRA', label: 'Maharashtra', sortOrder: 2 },
  { category: 'CONTRACTOR_CITY', code: 'AHMEDABAD', label: 'Ahmedabad', sortOrder: 1 },
  { category: 'CONTRACTOR_CITY', code: 'GANDHINAGAR', label: 'Gandhinagar', sortOrder: 2 },
  { category: 'CONTRACTOR_CITY', code: 'SURAT', label: 'Surat', sortOrder: 3 },
  { category: 'CONTRACTOR_DOCUMENT_TYPE', code: 'PAN', label: 'PAN Card', sortOrder: 1 },
  { category: 'CONTRACTOR_DOCUMENT_TYPE', code: 'GST', label: 'GST Certificate', sortOrder: 2 },
  { category: 'CONTRACTOR_DOCUMENT_TYPE', code: 'AGREEMENT', label: 'Agreement', sortOrder: 3 },
  { category: 'CONTRACTOR_DOCUMENT_TYPE', code: 'OTHER', label: 'Other', sortOrder: 4 },
];

export async function seedSystemLookups(prisma: PrismaClient) {
  for (const row of SEED) {
    await prisma.systemLookup.upsert({
      where: { category_code: { category: row.category, code: row.code } },
      create: row,
      update: { label: row.label, sortOrder: row.sortOrder },
    });
  }
  console.log(`Seeded ${SEED.length} system lookup options`);
}
