-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "allow_app" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "allow_browser" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "allow_browser_after_punch_in" BOOLEAN NOT NULL DEFAULT true;
