import 'package:flutter/material.dart';

/// Forces every Material glyph this app uses to stay in the web icon font.
/// Do not loop these — the tree-shaker only sees const Icon(...) / const IconData refs.
class MaterialIconKeepAlive extends StatelessWidget {
  const MaterialIconKeepAlive({super.key});

  @override
  Widget build(BuildContext context) {
    return const Offstage(
      child: Wrap(
        children: [
          Icon(Icons.account_balance, size: 0.001),
          Icon(Icons.account_balance_rounded, size: 0.001),
          Icon(Icons.account_balance_wallet_outlined, size: 0.001),
          Icon(Icons.account_tree, size: 0.001),
          Icon(Icons.account_tree_outlined, size: 0.001),
          Icon(Icons.account_tree_rounded, size: 0.001),
          Icon(Icons.add, size: 0.001),
          Icon(Icons.add_business_rounded, size: 0.001),
          Icon(Icons.add_circle_outline_rounded, size: 0.001),
          Icon(Icons.add_location_alt_rounded, size: 0.001),
          Icon(Icons.add_rounded, size: 0.001),
          Icon(Icons.alternate_email_rounded, size: 0.001),
          Icon(Icons.apartment_rounded, size: 0.001),
          Icon(Icons.add_task_rounded, size: 0.001),
          Icon(Icons.admin_panel_settings_outlined, size: 0.001),
          Icon(Icons.admin_panel_settings_rounded, size: 0.001),
          Icon(Icons.analytics_rounded, size: 0.001),
          Icon(Icons.apartment, size: 0.001),
          Icon(Icons.apartment_outlined, size: 0.001),
          Icon(Icons.apartment_rounded, size: 0.001),
          Icon(Icons.apps_rounded, size: 0.001),
          Icon(Icons.arrow_back, size: 0.001),
          Icon(Icons.arrow_back_rounded, size: 0.001),
          Icon(Icons.arrow_drop_down_rounded, size: 0.001),
          Icon(Icons.arrow_forward_rounded, size: 0.001),
          Icon(Icons.assignment_turned_in, size: 0.001),
          Icon(Icons.assignment_turned_in_outlined, size: 0.001),
          Icon(Icons.assignment_turned_in_rounded, size: 0.001),
          Icon(Icons.attach_file, size: 0.001),
          Icon(Icons.attach_file_outlined, size: 0.001),
          Icon(Icons.attach_file_rounded, size: 0.001),
          Icon(Icons.auto_awesome_rounded, size: 0.001),
          Icon(Icons.badge_outlined, size: 0.001),
          Icon(Icons.badge_rounded, size: 0.001),
          Icon(Icons.battery_alert, size: 0.001),
          Icon(Icons.battery_charging_full, size: 0.001),
          Icon(Icons.beach_access, size: 0.001),
          Icon(Icons.beach_access_rounded, size: 0.001),
          Icon(Icons.block, size: 0.001),
          Icon(Icons.broken_image_outlined, size: 0.001),
          Icon(Icons.business_center_rounded, size: 0.001),
          Icon(Icons.business_rounded, size: 0.001),
          Icon(Icons.cake_outlined, size: 0.001),
          Icon(Icons.calculate_outlined, size: 0.001),
          Icon(Icons.calendar_month_outlined, size: 0.001),
          Icon(Icons.calendar_month_rounded, size: 0.001),
          Icon(Icons.calendar_today, size: 0.001),
          Icon(Icons.calendar_today_outlined, size: 0.001),
          Icon(Icons.calendar_today_rounded, size: 0.001),
          Icon(Icons.calendar_view_day_rounded, size: 0.001),
          Icon(Icons.call, size: 0.001),
          Icon(Icons.call_end, size: 0.001),
          Icon(Icons.call_end_rounded, size: 0.001),
          Icon(Icons.call_rounded, size: 0.001),
          Icon(Icons.phone, size: 0.001),
          Icon(Icons.phone_rounded, size: 0.001),
          Icon(Icons.phone_in_talk_rounded, size: 0.001),
          Icon(Icons.camera_alt_rounded, size: 0.001),
          Icon(Icons.campaign_rounded, size: 0.001),
          Icon(Icons.cancel_outlined, size: 0.001),
          Icon(Icons.category_rounded, size: 0.001),
          Icon(Icons.celebration_rounded, size: 0.001),
          Icon(Icons.cell_tower, size: 0.001),
          Icon(Icons.chat_bubble, size: 0.001),
          Icon(Icons.chat_bubble_outline, size: 0.001),
          Icon(Icons.chat_bubble_outline_rounded, size: 0.001),
          Icon(Icons.chat_bubble_rounded, size: 0.001),
          Icon(Icons.check_box_outline_blank_rounded, size: 0.001),
          Icon(Icons.check_box_rounded, size: 0.001),
          Icon(Icons.check_circle, size: 0.001),
          Icon(Icons.check_circle_outline, size: 0.001),
          Icon(Icons.check_circle_rounded, size: 0.001),
          Icon(Icons.check_rounded, size: 0.001),
          Icon(Icons.checklist_rounded, size: 0.001),
          Icon(Icons.chevron_left, size: 0.001),
          Icon(Icons.chevron_left_rounded, size: 0.001),
          Icon(Icons.chevron_right, size: 0.001),
          Icon(Icons.chevron_right_rounded, size: 0.001),
          Icon(Icons.circle, size: 0.001),
          Icon(Icons.circle_outlined, size: 0.001),
          Icon(Icons.clear, size: 0.001),
          Icon(Icons.clear_rounded, size: 0.001),
          Icon(Icons.close, size: 0.001),
          Icon(Icons.close_rounded, size: 0.001),
          Icon(Icons.cloud_off_rounded, size: 0.001),
          Icon(Icons.cloud_upload_outlined, size: 0.001),
          Icon(Icons.contact_mail_outlined, size: 0.001),
          Icon(Icons.copy_rounded, size: 0.001),
          Icon(Icons.dark_mode, size: 0.001),
          Icon(Icons.dark_mode_rounded, size: 0.001),
          Icon(Icons.dashboard, size: 0.001),
          Icon(Icons.dashboard_outlined, size: 0.001),
          Icon(Icons.dashboard_rounded, size: 0.001),
          Icon(Icons.date_range_rounded, size: 0.001),
          Icon(Icons.delete_outline, size: 0.001),
          Icon(Icons.delete_outline_rounded, size: 0.001),
          Icon(Icons.delete_rounded, size: 0.001),
          Icon(Icons.description_outlined, size: 0.001),
          Icon(Icons.description_rounded, size: 0.001),
          Icon(Icons.device_hub_rounded, size: 0.001),
          Icon(Icons.difference_outlined, size: 0.001),
          Icon(Icons.directions_car, size: 0.001),
          Icon(Icons.done, size: 0.001),
          Icon(Icons.done_all, size: 0.001),
          Icon(Icons.download_outlined, size: 0.001),
          Icon(Icons.download_rounded, size: 0.001),
          Icon(Icons.draw_outlined, size: 0.001),
          Icon(Icons.edit_document, size: 0.001),
          Icon(Icons.edit_note, size: 0.001),
          Icon(Icons.edit_note_outlined, size: 0.001),
          Icon(Icons.edit_note_rounded, size: 0.001),
          Icon(Icons.edit_outlined, size: 0.001),
          Icon(Icons.edit_rounded, size: 0.001),
          Icon(Icons.emoji_emotions, size: 0.001),
          Icon(Icons.emoji_emotions_outlined, size: 0.001),
          Icon(Icons.error_outline, size: 0.001),
          Icon(Icons.error_outline_rounded, size: 0.001),
          Icon(Icons.error_rounded, size: 0.001),
          Icon(Icons.event, size: 0.001),
          Icon(Icons.event_available, size: 0.001),
          Icon(Icons.event_available_outlined, size: 0.001),
          Icon(Icons.event_available_rounded, size: 0.001),
          Icon(Icons.event_busy_rounded, size: 0.001),
          Icon(Icons.event_rounded, size: 0.001),
          Icon(Icons.expand_less, size: 0.001),
          Icon(Icons.expand_less_rounded, size: 0.001),
          Icon(Icons.expand_more, size: 0.001),
          Icon(Icons.expand_more_rounded, size: 0.001),
          Icon(Icons.fiber_manual_record, size: 0.001),
          Icon(Icons.filter_list_rounded, size: 0.001),
          Icon(Icons.fingerprint, size: 0.001),
          Icon(Icons.fingerprint_outlined, size: 0.001),
          Icon(Icons.fingerprint_rounded, size: 0.001),
          Icon(Icons.fit_screen_rounded, size: 0.001),
          Icon(Icons.flag, size: 0.001),
          Icon(Icons.flag_rounded, size: 0.001),
          Icon(Icons.folder_open_rounded, size: 0.001),
          Icon(Icons.folder_shared_rounded, size: 0.001),
          Icon(Icons.gpp_bad_rounded, size: 0.001),
          Icon(Icons.gps_fixed, size: 0.001),
          Icon(Icons.gps_off, size: 0.001),
          Icon(Icons.grid_view_rounded, size: 0.001),
          Icon(Icons.group_add_rounded, size: 0.001),
          Icon(Icons.group_outlined, size: 0.001),
          Icon(Icons.groups_2_rounded, size: 0.001),
          Icon(Icons.groups_rounded, size: 0.001),
          Icon(Icons.hide_image_outlined, size: 0.001),
          Icon(Icons.history, size: 0.001),
          Icon(Icons.history_edu_outlined, size: 0.001),
          Icon(Icons.history_edu_rounded, size: 0.001),
          Icon(Icons.history_rounded, size: 0.001),
          Icon(Icons.history_toggle_off_rounded, size: 0.001),
          Icon(Icons.home, size: 0.001),
          Icon(Icons.home_outlined, size: 0.001),
          Icon(Icons.hourglass_top, size: 0.001),
          Icon(Icons.hourglass_top_rounded, size: 0.001),
          Icon(Icons.how_to_reg_outlined, size: 0.001),
          Icon(Icons.hub_rounded, size: 0.001),
          Icon(Icons.image_outlined, size: 0.001),
          Icon(Icons.image_rounded, size: 0.001),
          Icon(Icons.inbox_outlined, size: 0.001),
          Icon(Icons.info_outline, size: 0.001),
          Icon(Icons.info_outline_rounded, size: 0.001),
          Icon(Icons.insert_drive_file_outlined, size: 0.001),
          Icon(Icons.insert_drive_file_rounded, size: 0.001),
          Icon(Icons.insights, size: 0.001),
          Icon(Icons.insights_outlined, size: 0.001),
          Icon(Icons.key_rounded, size: 0.001),
          Icon(Icons.key_outlined, size: 0.001),
          Icon(Icons.keyboard_arrow_down, size: 0.001),
          Icon(Icons.keyboard_arrow_left, size: 0.001),
          Icon(Icons.keyboard_arrow_right, size: 0.001),
          Icon(Icons.keyboard_arrow_up, size: 0.001),
          Icon(Icons.layers_outlined, size: 0.001),
          Icon(Icons.light_mode, size: 0.001),
          Icon(Icons.light_mode_rounded, size: 0.001),
          Icon(Icons.link_off_rounded, size: 0.001),
          Icon(Icons.link_rounded, size: 0.001),
          Icon(Icons.list_alt_rounded, size: 0.001),
          Icon(Icons.location_city_rounded, size: 0.001),
          Icon(Icons.location_on, size: 0.001),
          Icon(Icons.location_on_outlined, size: 0.001),
          Icon(Icons.lock_open_rounded, size: 0.001),
          Icon(Icons.lock_outline, size: 0.001),
          Icon(Icons.lock_outline_rounded, size: 0.001),
          Icon(Icons.login_rounded, size: 0.001),
          Icon(Icons.logout, size: 0.001),
          Icon(Icons.logout_rounded, size: 0.001),
          Icon(Icons.mail_outline, size: 0.001),
          Icon(Icons.manage_accounts, size: 0.001),
          Icon(Icons.manage_accounts_outlined, size: 0.001),
          Icon(Icons.manage_accounts_rounded, size: 0.001),
          Icon(Icons.map_rounded, size: 0.001),
          Icon(Icons.mark_email_unread_outlined, size: 0.001),
          Icon(Icons.menu_book_outlined, size: 0.001),
          Icon(Icons.menu_open_rounded, size: 0.001),
          Icon(Icons.menu_rounded, size: 0.001),
          Icon(Icons.mic_off_rounded, size: 0.001),
          Icon(Icons.mic_rounded, size: 0.001),
          Icon(Icons.my_location_rounded, size: 0.001),
          Icon(Icons.notes, size: 0.001),
          Icon(Icons.notes_outlined, size: 0.001),
          Icon(Icons.notes_rounded, size: 0.001),
          Icon(Icons.open_in_new, size: 0.001),
          Icon(Icons.open_in_new_rounded, size: 0.001),
          Icon(Icons.pause, size: 0.001),
          Icon(Icons.payments_outlined, size: 0.001),
          Icon(Icons.payments_rounded, size: 0.001),
          Icon(Icons.pending_actions_rounded, size: 0.001),
          Icon(Icons.people, size: 0.001),
          Icon(Icons.people_alt_rounded, size: 0.001),
          Icon(Icons.people_outline, size: 0.001),
          Icon(Icons.people_outline_rounded, size: 0.001),
          Icon(Icons.people_rounded, size: 0.001),
          Icon(Icons.perm_media_outlined, size: 0.001),
          Icon(Icons.person, size: 0.001),
          Icon(Icons.person_add_alt_1, size: 0.001),
          Icon(Icons.person_add_alt_1_rounded, size: 0.001),
          Icon(Icons.person_add_outlined, size: 0.001),
          Icon(Icons.person_add_rounded, size: 0.001),
          Icon(Icons.person_outline, size: 0.001),
          Icon(Icons.person_pin_circle_rounded, size: 0.001),
          Icon(Icons.person_rounded, size: 0.001),
          Icon(Icons.person_search_rounded, size: 0.001),
          Icon(Icons.photo_camera_back, size: 0.001),
          Icon(Icons.photo_outlined, size: 0.001),
          Icon(Icons.picture_as_pdf_outlined, size: 0.001),
          Icon(Icons.picture_as_pdf_rounded, size: 0.001),
          Icon(Icons.pin_drop_outlined, size: 0.001),
          Icon(Icons.pin_outlined, size: 0.001),
          Icon(Icons.pin_rounded, size: 0.001),
          Icon(Icons.play_arrow, size: 0.001),
          Icon(Icons.play_circle_rounded, size: 0.001),
          Icon(Icons.present_to_all, size: 0.001),
          Icon(Icons.radio_button_checked, size: 0.001),
          Icon(Icons.radio_button_checked_rounded, size: 0.001),
          Icon(Icons.radio_button_off, size: 0.001),
          Icon(Icons.radio_button_unchecked, size: 0.001),
          Icon(Icons.radio_button_unchecked_rounded, size: 0.001),
          Icon(Icons.receipt_long_outlined, size: 0.001),
          Icon(Icons.receipt_long_rounded, size: 0.001),
          Icon(Icons.refresh, size: 0.001),
          Icon(Icons.refresh_rounded, size: 0.001),
          Icon(Icons.remove_circle_outline, size: 0.001),
          Icon(Icons.remove_circle_outline_rounded, size: 0.001),
          Icon(Icons.remove_rounded, size: 0.001),
          Icon(Icons.reply_rounded, size: 0.001),
          Icon(Icons.restart_alt, size: 0.001),
          Icon(Icons.restart_alt_rounded, size: 0.001),
          Icon(Icons.route, size: 0.001),
          Icon(Icons.route_outlined, size: 0.001),
          Icon(Icons.rule_rounded, size: 0.001),
          Icon(Icons.run_circle, size: 0.001),
          Icon(Icons.save_outlined, size: 0.001),
          Icon(Icons.save_rounded, size: 0.001),
          Icon(Icons.schedule, size: 0.001),
          Icon(Icons.schedule_rounded, size: 0.001),
          Icon(Icons.school_outlined, size: 0.001),
          Icon(Icons.screen_share_rounded, size: 0.001),
          Icon(Icons.search, size: 0.001),
          Icon(Icons.search_off_rounded, size: 0.001),
          Icon(Icons.search_rounded, size: 0.001),
          Icon(Icons.send, size: 0.001),
          Icon(Icons.send_rounded, size: 0.001),
          Icon(Icons.settings, size: 0.001),
          Icon(Icons.settings_applications, size: 0.001),
          Icon(Icons.settings_applications_rounded, size: 0.001),
          Icon(Icons.settings_outlined, size: 0.001),
          Icon(Icons.settings_rounded, size: 0.001),
          Icon(Icons.shield, size: 0.001),
          Icon(Icons.shield_outlined, size: 0.001),
          Icon(Icons.shield_rounded, size: 0.001),
          Icon(Icons.star_border, size: 0.001),
          Icon(Icons.star_rounded, size: 0.001),
          Icon(Icons.stop_screen_share_rounded, size: 0.001),
          Icon(Icons.storage_rounded, size: 0.001),
          Icon(Icons.support_agent_outlined, size: 0.001),
          Icon(Icons.support_agent_rounded, size: 0.001),
          Icon(Icons.swap_horiz_rounded, size: 0.001),
          Icon(Icons.sync_rounded, size: 0.001),
          Icon(Icons.task_alt, size: 0.001),
          Icon(Icons.task_alt_outlined, size: 0.001),
          Icon(Icons.task_alt_rounded, size: 0.001),
          Icon(Icons.timeline, size: 0.001),
          Icon(Icons.timeline_rounded, size: 0.001),
          Icon(Icons.timer, size: 0.001),
          Icon(Icons.timer_outlined, size: 0.001),
          Icon(Icons.timer_rounded, size: 0.001),
          Icon(Icons.title_rounded, size: 0.001),
          Icon(Icons.trending_up_rounded, size: 0.001),
          Icon(Icons.tune_rounded, size: 0.001),
          Icon(Icons.undo, size: 0.001),
          Icon(Icons.undo_rounded, size: 0.001),
          Icon(Icons.upload_file, size: 0.001),
          Icon(Icons.upload_file_outlined, size: 0.001),
          Icon(Icons.upload_file_rounded, size: 0.001),
          Icon(Icons.verified_outlined, size: 0.001),
          Icon(Icons.verified_user_rounded, size: 0.001),
          Icon(Icons.videocam, size: 0.001),
          Icon(Icons.videocam_off_outlined, size: 0.001),
          Icon(Icons.videocam_off_rounded, size: 0.001),
          Icon(Icons.videocam_outlined, size: 0.001),
          Icon(Icons.videocam_rounded, size: 0.001),
          Icon(Icons.view_column_outlined, size: 0.001),
          Icon(Icons.view_timeline_outlined, size: 0.001),
          Icon(Icons.visibility_off_outlined, size: 0.001),
          Icon(Icons.visibility_outlined, size: 0.001),
          Icon(Icons.wallpaper_rounded, size: 0.001),
          Icon(Icons.warning, size: 0.001),
          Icon(Icons.warning_amber, size: 0.001),
          Icon(Icons.warning_amber_rounded, size: 0.001),
          Icon(Icons.wifi_off, size: 0.001),
          Icon(Icons.work_history_outlined, size: 0.001),
          Icon(Icons.work_outline, size: 0.001),
          Icon(Icons.work_outline_rounded, size: 0.001),
          Icon(Icons.work_rounded, size: 0.001),
        ],
      ),
    );
  }
}

const kRetainedMaterialIcons = <IconData>[
  Icons.account_balance,
  Icons.account_balance_rounded,
  Icons.account_balance_wallet_outlined,
  Icons.account_tree,
  Icons.account_tree_outlined,
  Icons.account_tree_rounded,
  Icons.add,
  Icons.add_business_rounded,
  Icons.add_circle_outline_rounded,
  Icons.add_location_alt_rounded,
  Icons.add_rounded,
  Icons.alternate_email_rounded,
  Icons.add_task_rounded,
  Icons.admin_panel_settings_outlined,
  Icons.admin_panel_settings_rounded,
  Icons.analytics_rounded,
  Icons.apartment,
  Icons.apartment_outlined,
  Icons.apartment_rounded,
  Icons.apps_rounded,
  Icons.arrow_back,
  Icons.arrow_back_rounded,
  Icons.arrow_drop_down_rounded,
  Icons.arrow_forward_rounded,
  Icons.assignment_turned_in,
  Icons.assignment_turned_in_outlined,
  Icons.assignment_turned_in_rounded,
  Icons.attach_file,
  Icons.attach_file_outlined,
  Icons.attach_file_rounded,
  Icons.auto_awesome_rounded,
  Icons.badge_outlined,
  Icons.badge_rounded,
  Icons.battery_alert,
  Icons.battery_charging_full,
  Icons.beach_access,
  Icons.beach_access_rounded,
  Icons.block,
  Icons.broken_image_outlined,
  Icons.business_center_rounded,
  Icons.business_rounded,
  Icons.cake_outlined,
  Icons.calculate_outlined,
  Icons.calendar_month_outlined,
  Icons.calendar_month_rounded,
  Icons.calendar_today,
  Icons.calendar_today_outlined,
  Icons.calendar_today_rounded,
  Icons.calendar_view_day_rounded,
  Icons.call,
  Icons.call_end,
  Icons.call_end_rounded,
  Icons.call_rounded,
  Icons.phone,
  Icons.phone_rounded,
  Icons.phone_in_talk_rounded,
  Icons.camera_alt_rounded,
  Icons.campaign_rounded,
  Icons.cancel_outlined,
  Icons.category_rounded,
  Icons.celebration_rounded,
  Icons.cell_tower,
  Icons.chat_bubble,
  Icons.chat_bubble_outline,
  Icons.chat_bubble_outline_rounded,
  Icons.chat_bubble_rounded,
  Icons.check_box_outline_blank_rounded,
  Icons.check_box_rounded,
  Icons.check_circle,
  Icons.check_circle_outline,
  Icons.check_circle_rounded,
  Icons.check_rounded,
  Icons.checklist_rounded,
  Icons.chevron_left,
  Icons.chevron_left_rounded,
  Icons.chevron_right,
  Icons.chevron_right_rounded,
  Icons.circle,
  Icons.circle_outlined,
  Icons.clear,
  Icons.clear_rounded,
  Icons.close,
  Icons.close_rounded,
  Icons.cloud_off_rounded,
  Icons.cloud_upload_outlined,
  Icons.contact_mail_outlined,
  Icons.copy_rounded,
  Icons.dark_mode,
  Icons.dark_mode_rounded,
  Icons.dashboard,
  Icons.dashboard_outlined,
  Icons.dashboard_rounded,
  Icons.date_range_rounded,
  Icons.delete_outline,
  Icons.delete_outline_rounded,
  Icons.delete_rounded,
  Icons.description_outlined,
  Icons.description_rounded,
  Icons.device_hub_rounded,
  Icons.difference_outlined,
  Icons.directions_car,
  Icons.done,
  Icons.done_all,
  Icons.download_outlined,
  Icons.download_rounded,
  Icons.draw_outlined,
  Icons.edit_document,
  Icons.edit_note,
  Icons.edit_note_outlined,
  Icons.edit_note_rounded,
  Icons.edit_outlined,
  Icons.edit_rounded,
  Icons.emoji_emotions,
  Icons.emoji_emotions_outlined,
  Icons.error_outline,
  Icons.error_outline_rounded,
  Icons.error_rounded,
  Icons.event,
  Icons.event_available,
  Icons.event_available_outlined,
  Icons.event_available_rounded,
  Icons.event_busy_rounded,
  Icons.event_rounded,
  Icons.expand_less,
  Icons.expand_less_rounded,
  Icons.expand_more,
  Icons.expand_more_rounded,
  Icons.fiber_manual_record,
  Icons.filter_list_rounded,
  Icons.fingerprint,
  Icons.fingerprint_outlined,
  Icons.fingerprint_rounded,
  Icons.fit_screen_rounded,
  Icons.flag,
  Icons.flag_rounded,
  Icons.folder_open_rounded,
  Icons.folder_shared_rounded,
  Icons.gpp_bad_rounded,
  Icons.gps_fixed,
  Icons.gps_off,
  Icons.grid_view_rounded,
  Icons.group_add_rounded,
  Icons.group_outlined,
  Icons.groups_2_rounded,
  Icons.groups_rounded,
  Icons.hide_image_outlined,
  Icons.history,
  Icons.history_edu_outlined,
  Icons.history_edu_rounded,
  Icons.history_rounded,
  Icons.history_toggle_off_rounded,
  Icons.home,
  Icons.home_outlined,
  Icons.hourglass_top,
  Icons.hourglass_top_rounded,
  Icons.how_to_reg_outlined,
  Icons.hub_rounded,
  Icons.image_outlined,
  Icons.image_rounded,
  Icons.inbox_outlined,
  Icons.info_outline,
  Icons.info_outline_rounded,
  Icons.insert_drive_file_outlined,
  Icons.insert_drive_file_rounded,
  Icons.insights,
  Icons.insights_outlined,
  Icons.key_rounded,
  Icons.key_outlined,
  Icons.keyboard_arrow_down,
  Icons.keyboard_arrow_left,
  Icons.keyboard_arrow_right,
  Icons.keyboard_arrow_up,
  Icons.layers_outlined,
  Icons.light_mode,
  Icons.light_mode_rounded,
  Icons.link_off_rounded,
  Icons.link_rounded,
  Icons.list_alt_rounded,
  Icons.location_city_rounded,
  Icons.location_on,
  Icons.location_on_outlined,
  Icons.lock_open_rounded,
  Icons.lock_outline,
  Icons.lock_outline_rounded,
  Icons.login_rounded,
  Icons.logout,
  Icons.logout_rounded,
  Icons.mail_outline,
  Icons.manage_accounts,
  Icons.manage_accounts_outlined,
  Icons.manage_accounts_rounded,
  Icons.map_rounded,
  Icons.mark_email_unread_outlined,
  Icons.menu_book_outlined,
  Icons.menu_open_rounded,
  Icons.menu_rounded,
  Icons.mic_off_rounded,
  Icons.mic_rounded,
  Icons.my_location_rounded,
  Icons.notes,
  Icons.notes_outlined,
  Icons.notes_rounded,
  Icons.open_in_new,
  Icons.open_in_new_rounded,
  Icons.pause,
  Icons.payments_outlined,
  Icons.payments_rounded,
  Icons.pending_actions_rounded,
  Icons.people,
  Icons.people_alt_rounded,
  Icons.people_outline,
  Icons.people_outline_rounded,
  Icons.people_rounded,
  Icons.perm_media_outlined,
  Icons.person,
  Icons.person_add_alt_1,
  Icons.person_add_alt_1_rounded,
  Icons.person_add_outlined,
  Icons.person_add_rounded,
  Icons.person_outline,
  Icons.person_pin_circle_rounded,
  Icons.person_rounded,
  Icons.person_search_rounded,
  Icons.photo_camera_back,
  Icons.photo_outlined,
  Icons.picture_as_pdf_outlined,
  Icons.picture_as_pdf_rounded,
  Icons.pin_drop_outlined,
  Icons.pin_outlined,
  Icons.pin_rounded,
  Icons.play_arrow,
  Icons.play_circle_rounded,
  Icons.present_to_all,
  Icons.radio_button_checked,
  Icons.radio_button_checked_rounded,
  Icons.radio_button_off,
  Icons.radio_button_unchecked,
  Icons.radio_button_unchecked_rounded,
  Icons.receipt_long_outlined,
  Icons.receipt_long_rounded,
  Icons.refresh,
  Icons.refresh_rounded,
  Icons.remove_circle_outline,
  Icons.remove_circle_outline_rounded,
  Icons.remove_rounded,
  Icons.reply_rounded,
  Icons.restart_alt,
  Icons.restart_alt_rounded,
  Icons.route,
  Icons.route_outlined,
  Icons.rule_rounded,
  Icons.run_circle,
  Icons.save_outlined,
  Icons.save_rounded,
  Icons.schedule,
  Icons.schedule_rounded,
  Icons.school_outlined,
  Icons.screen_share_rounded,
  Icons.search,
  Icons.search_off_rounded,
  Icons.search_rounded,
  Icons.send,
  Icons.send_rounded,
  Icons.settings,
  Icons.settings_applications,
  Icons.settings_applications_rounded,
  Icons.settings_outlined,
  Icons.settings_rounded,
  Icons.shield,
  Icons.shield_outlined,
  Icons.shield_rounded,
  Icons.star_border,
  Icons.star_rounded,
  Icons.stop_screen_share_rounded,
  Icons.storage_rounded,
  Icons.support_agent_outlined,
  Icons.support_agent_rounded,
  Icons.swap_horiz_rounded,
  Icons.sync_rounded,
  Icons.task_alt,
  Icons.task_alt_outlined,
  Icons.task_alt_rounded,
  Icons.timeline,
  Icons.timeline_rounded,
  Icons.timer,
  Icons.timer_outlined,
  Icons.timer_rounded,
  Icons.title_rounded,
  Icons.trending_up_rounded,
  Icons.tune_rounded,
  Icons.undo,
  Icons.undo_rounded,
  Icons.upload_file,
  Icons.upload_file_outlined,
  Icons.upload_file_rounded,
  Icons.verified_outlined,
  Icons.verified_user_rounded,
  Icons.videocam,
  Icons.videocam_off_outlined,
  Icons.videocam_off_rounded,
  Icons.videocam_outlined,
  Icons.videocam_rounded,
  Icons.view_column_outlined,
  Icons.view_timeline_outlined,
  Icons.visibility_off_outlined,
  Icons.visibility_outlined,
  Icons.wallpaper_rounded,
  Icons.warning,
  Icons.warning_amber,
  Icons.warning_amber_rounded,
  Icons.wifi_off,
  Icons.work_history_outlined,
  Icons.work_outline,
  Icons.work_outline_rounded,
  Icons.work_rounded,
];

void retainMaterialIconGlyphs() {
  if (kRetainedMaterialIcons.isEmpty) {
    throw StateError('Material icon retain list is empty');
  }
}

